services:
  veeam-cleaner:
    container_name: veeam-cleaner
    build: .
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ${BACKUPS_HOST_PATH:-./backups}:/backups
    command: ["--path", "/backups"]
