services:
  veeam-cleaner:
    container_name: veeam-cleaner
    build: .
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./logs:/app/logs
      - /mnt/veeambackup:/backups   # <-- Aquí está tu NAS montada
    user: root
    command: ["--path", "/backups"]  # Ejecuta el dry run por defecto
