services:
  veeam-cleaner:
    container_name: veeam-cleaner
    build: .
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - /mnt/veeambackup:/backups
    command: ["--path", "/backups"]
